package:
  name: flask_authzn
  version: "0.0.24"

source:
  git_url: git@github.com:slaclab/flask_authnz.git
  git_tag: "0.0.24"

build:
  noarch: python
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

about:
  home: https://github.com/slaclab/flask_authzn
  license: MIT License
